spring:
  application:
    name: springboot
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: public
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/Dev?currentSchema=public
    url: jdbc:postgresql://planes-test-db-1.cvao6k0qkgoq.eu-north-1.rds.amazonaws.com/planes-test-db-1?currentSchema=public
    username: postgres
    password: SECRET
  # jpa:
    # show-sql: true