apiVersion: v1
kind: Service
metadata:
  name: planes-management
spec:
  selector:
    app: db-viewer
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-viewer
  template:
    metadata:
      labels:
        app: db-viewer
    spec:
      containers:
        - name: app
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@mail.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "root"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: db-ingress
spec:
  rules:
    - host: "localhost"
      http:
        paths:
          - pathType: Prefix
            path: "/management/db"
            backend:
              service:
                name: planes-management
                port:
                  number: 80
---